#!/bin/sh
seed=$(bw -raw list items --search "$@" | jq -r '.[]|select(.type==1)|.login.totp' | sed 's!.*/!!' | grep -v "^null$")

set -- $seed
if [ $# != 1 ]
then
  echo Search matches multiple entries.  Aborted
  exit
fi
totpgen $seed
